function filter() {
    return [
    'Webcam models required',
    'Return Phone Calls!!!$2-$5K!!!+Per Month PT (Telecommute))',
    'Spanish Speakers Needed! Speech Collection',
    'blind singer seeking female driver/assistant must speak spanish ASAP',
    'female webcam modeling location available',
    'Web Development Immersion Program',
    'Small business owner? We build websites and manage social media',
    'Small business owner? We build websites and handle social media',
    'Any ladies or couples with webcams please get in touch',
    'Make !!!$2-$5K!!! In Residuals+Per Month PT (Telecommute)',
    'Webcam Models Required',
    'Have a spare room in your home? Get paid daily',
    'Are you a Website designer looking for office Space with no  rent',
    'Best Take Surveys Website!',
    '** ZERO SELLING: TEXT MARKETING: REMOTE REPS NEEDED: $200-$600/DAY **',
    '6-Figure Coaching Program *Make Money Online *Telecommute *Home Work',
    'TECH NEEDED TO PROGRAM REMOTE CONTROL',
    '¡Gane hasta $250 USD por 2.5h de trabajo! Buscamos hombres hispanos',
    '¡Gane hasta $250 USD por 2.5h de trabajo!  Buscamos hombres hispanos',
    'JavaScript Developer at craigslist',
    'Full Stack Web Developer at craigslist',
    'React Developer at craigslist',
    'Mobile App Developer at craigslist',
    'Machine Learning Developer at craigslist',
    'POSSIBLE MILLIONAIRE IN 12-36 MONTHS',
    '$$$ GET RID OF YOUR MONTHLY BILLS FAST $$$',
    '***** Get Paid Every WEEK! ***** (Across the US)',
    '" Be Your Own Boss" "Start Your Own Travel Business"⛵ ✈ 🚗',
    'adult content creators - female',
    'I need help with deep Web and bitcoin?',
    'BIG $$$ FAST - EZ TEXT SALES - $200 A POP- PAID DAILY (Work from home)',
    '▶ BIG $$ FAST - EZ TEXT SALES - $200 A POP (Work from home)',
    'Looking for people to test my new Weight Loss Competition App',
    'Tutoring needed for Apple MacBook Pro',
    '>>> WEBSITE TUTOR: 8 HRS/$300 <<<',
    'Local Web Designer (In Office Only!) 30 + Hr a Week',
    '20 mins chat for $30 with fabulous App users',
    'Extra Income - Weekly Pay - Weight Loss Coffee That Pays!',
    'Does your business need a website or social media marketing??',
    '*Remote Work* Product Testing Legal Online Casinos $100-1,000',
    'Remote Contract Attorney',
    'need Photoshop Lightroom tutor- remote',
    'Apple Watch App Study for Couples - $150',
    'Software Engineer, Automated Mapping | Toyota',
    'Make money playing RPG apps',
    'Appointment Setters (3 Positions Remaining)',
    'Appointment Setters Needed $10+ hr',
    '$50 Research Interviews on 4/14 (remote)',
    'Dev Ops Engineer - Join a THRIVING Company actively recruiting!!',
    'Local Free Website Building Class - Weekly',
    'Seeking Developer to Create MVP in Exchange for Equity',
    'Webcam girls needed asap',
    'How Hirng Appt Setters $10-$20+hr ( Only 3 Spots Left)',
    'will cashapp you $6 for a yelp review',
    'Appliance Repair Specialist',
    'webcam model 2,000 plus a week',
    'Appliance genius wanted',
    'Representatives Needed - Telecommute',
    'Social media posting and web data upload',
    'Work from home as a licensed insurance agent ALL WELCOME TO APPLY',
    '$100/week tech support for a virtual tutoring website',
    'Travel Coordinator Remote',
    'Day Trading Apprenticeship Opportunity',
    'Swift iOS Development',
    'Darknet / Darkweb Tutorial',
    ];
}

module.exports = filter();